const MEETING_STATUSES = [
  'PENDING',
  'UPLOADING',
  'PROCESSING',
  'TRANSCRIBING',
  'ANALYZING',
  'COMPLETED',
  'FAILED'
];

const TASK_STATUSES = ['TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED'];
const PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];

module.exports = {
  MEETING_STATUSES,
  TASK_STATUSES,
  PRIORITIES
};
